### PR TITLE
MM-60351 Use oEmbed for YouTube links 

### LINKED ISSUE #16429: Youtube Previews not working after upgrade
#### Summary
Youtube Previews not working after upgrade

#### Steps to reproduce
Paste URL to some YouTube video in a channel

#### Expected behavior
YouTube previews should work

#### Observed behavior (that appears unintentional) 
I have recently upgraded from 5.26 to 5.29 (using mattermost/mattermost-docker) and now YouTube previews do not work on either a desktop client (tested macOS, Linux & Windows) or a desktop web browser (tested Safari and Firefox). Curiously they DO work in the mobile application (tested iOS and Android clients). On the desktop, if I scroll back a few days before the upgrade occurred, the previews are still in place for those old posts.

#### Possible fixes
I will list things I have tried after reading previous posts that looked like they may be similar:
- System Console > SITE CONFIGURATION > Posts; ensured "Enable Link Previews" is set to True and ensured Google API key is populated
- Cut new Google API key
- Accessed shell of the app container; performed an `nslookup www.youtube.com` and `curl -k -I -L https://www.youtube.com` which returned IP addresses and a 200 response, respectively
- Ensured photo proxy is off as many suggestions referenced this; it was never on and should not be as I am not using an outbound proxy
- Checked `diff` of config.json; nothing sticks out to me https://pastebin.com/9EHtuqFe
- Enabled DEBUG level logging; tail'd the log file while posting YouTube links. Didn't see anything relevant printed

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
As I've stated in the Jira ticket and enough other places, YouTube has stopped serving OpenGraph metadata with their HTML for requests from certain places and user agents. Unfortunately, this affects any MM server running in a cloud provider from what I can tell.

I was worried we'd have to do something hacky or something that requires server admins to jump through hoops to get the same functionaly back, but thankfully, @fmartingr found that we can get the same information using oEmbed instead of Opengraph. I might have gone a bit overkill on making an oEmbed system that I think is super clean, but I also made it only limited to YouTube for now to avoid any security risks.

#### Ticket Link
MM-60351
Fixes #16429

#### Screenshots
I'm going to remove the ` (oEmbed Edition)` after people have had a chance to test this
Screenshot 2024-09-25 at 3 45 16 PM

#### Release Note
```release-note
Fixed YouTube previews no longer being displayed
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

File: server/channels/app/oembed/providers.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
```
Comment (streamer45) [inline server/channels/app/oembed/providers.go:1]: It's good practice to use a `_gen.go` suffix for generated code. It would also make it consistent with other files we generate (e.g. https://github.com/mattermost/mattermost/blob/master/server/public/model/user_serial_gen.go and the like)

File: server/channels/app/oembed/endpoint.go [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+	query.Add("format", "json")
+	query.Add("url", requestURL)
+	url.RawQuery = query.Encode()
+
+	return url.String()
+}
+
+// FindEndpointForURL returns a ProviderEndpoint for a given URL if it matches one that's supported by us. Returns nil
+// if none of the supported providers match the given URL.
+func FindEndpointForURL(requestURL string) *ProviderEndpoint {
```
Comment (streamer45) [inline server/channels/app/oembed/endpoint.go:32]: Is this going to be a performance concern? 

- Should we add a benchmark?
- Should we consider caching?

It's fine if the answer is no to the above, having the single provider and the regexp being precompiled should help. What I am not sure about is how frequently we'd be calling this from the app side.

File: server/channels/app/oembed/oembed.go [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+	// Fields that are required for responses of the type "video" or "rich"
+	HTML string `json:"html"`
+
+	// Fields that are required for responses with the type "photo", "video", or "rich"
+	Width  int `json:"width"`
+	Height int `json:"height"`
+}
+
+func ResponseFromJson(r io.Reader) (*OEmbedResponse, error) {
```
Comment (streamer45) [inline server/channels/app/oembed/oembed.go:39]: `ResponseFromJSON` would be more idiomatic.

File: server/channels/app/oembed/oembed.go [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+	var response OEmbedResponse
+
+	err := json.NewDecoder(r).Decode(&response)
+	if err != nil {
+		return nil, err
+	}
+
+	// Do a quick smoke test to confirm that this is hopefully a valid oEmbed response
+	if response.Version != "1.0" {
```
Comment (streamer45) [inline server/channels/app/oembed/oembed.go:48]: Should we consider a `func (r *OEmbedResponse) IsValid() error` method perhaps?

File: server/channels/app/opengraph.go [hunk 5]
```diff
@@ -144,3 +147,31 @@ func openGraphDecodeHTMLEntities(og *opengraph.OpenGraph) {
...
+
+func (a *App) parseOpenGraphFromOEmbed(requestURL string, body io.Reader) (*opengraph.OpenGraph, error) {
+	oEmbedResponse, err := oembed.ResponseFromJson(io.LimitReader(body, MaxOpenGraphResponseSize))
+	if err != nil {
+		return nil, errors.Wrap(err, "parseOpenGraphFromOEmbed: Unable to parse oEmbed response")
+	}
+
+	og := &opengraph.OpenGraph{
+		Type:  "opengraph",
+		Title: oEmbedResponse.Title + " (oEmbed Edition)", // TODO remove this before merging the PR
```
Comment (streamer45) [inline server/channels/app/opengraph.go:159]: Is it time to follow up on the TODO?

**Review by streamer45 — COMMENTED** [review]
Nice work! Nothing truly blocking, just some questions and suggestions.

File: server/channels/app/oembed/generator/providers_generator.go [hunk 6]
```diff
@@ -0,0 +1,161 @@
...
+
+type oEmbedEndpoint struct {
+	Schemes   []string `json:"schemes,omitempty"`
+	URL       string   `json:"url"`
+	Discovery bool     `json:"discovery,omitempty"`
+	Formats   []string `json:"formats,omitempty"`
+}
+
+func main() {
+	inputJson, err := os.ReadFile("./generator/providers.json")
```
[the remark this answers is not in the document]
Comment (hmhealey) [reply server/channels/app/oembed/generator/providers_generator.go:46]: I can add a comment on how to get the file, but I didn't want to check it in because it's a third party dependency that may change. It's available at https://oembed.com/providers.json and as an NPM package, but since we need it from the Go side, I didn't want to use those.

As for the rest of the process, I can write a bit about that, but I don't expect us to update this very often though. I don't have any plans to flesh out oEmbed support at the moment, but I do want us to set us up for it if we want to do it in the future

File: server/channels/app/oembed/endpoint.go (hunk 2 above)
Comment (hmhealey) [reply server/channels/app/oembed/endpoint.go:32]: No, I don't expect it to be a performance concern. This is called by `App.getLinkMetadata` whenever the server sends posts to the client, but because `getLinkMetadata` caches its results, this should only ever be called once per post (outside of very rare cases but that code is idempotent so that's acceptable). Even when this is called, it's followed by an HTTP request to a third party server regardless of the result, and that'd have a relatively much larger effect.

To answer your questions more directly, I'd say no to benchmarks and it's basically already cached

File: server/channels/app/oembed/oembed.go (hunk 3 above)
Comment (hmhealey) [reply server/channels/app/oembed/oembed.go:39]: Good catch! I did my best to follow the Go convention here, but it's hard when JS uses the opposite

File: server/channels/app/oembed/oembed.go (hunk 4 above)
Comment (hmhealey) [reply server/channels/app/oembed/oembed.go:48]: I was considering it since I was thinking about building this as a standalone package, but I don't think it's needed at the moment since I would trust YouTube on it. There's some other things we could check for validity based on [the oEmbed spec](https://oembed.com/), but the version check should be enough to confirm that we've hopefully hit a real oEmbed endpoint

File: server/channels/app/opengraph.go (hunk 5 above)
Comment (hmhealey) [reply server/channels/app/opengraph.go:159]: Yeah, I can remove that. I was thinking of leaving it until QA testing, but that's not needed

**Review by streamer45 — APPROVED** [review]

**Review by fmartingr — APPROVED** [review]
Awesome work!

File: server/channels/app/oembed/generator/providers_generator.go [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+	partsPattern := regexp.MustCompile(`^(\w+:(?://)?)([^/]*)(/[^?]*)?(\?[^?]*)?$`)
+	parts := partsPattern.FindStringSubmatch(scheme)
+	if parts == nil {
+		return nil, fmt.Errorf("unable to split scheme %s into parts", scheme)
+	} else if len(parts) != 5 {
+		return nil, fmt.Errorf("wrong number of parts for scheme %s", scheme)
+	}
+
+	protocol := parts[1]
+	if protocol != "http://" && protocol != "https://" && protocol != "spotify:" {
```
Comment (esarafianou) [inline server/channels/app/oembed/generator/providers_generator.go:131]: Why do we need spotify? Isn't that only of youtube?

**Review by esarafianou — APPROVED** [review]
LGTM. Just a question for my understanding

File: server/channels/app/oembed/generator/providers_generator.go (hunk 7 above)
Comment (hmhealey) [reply server/channels/app/oembed/generator/providers_generator.go:131]: Even though we're not using any other providers, I wanted this function to be able to handle every pattern in providers.json to make it more future proof. I was also thinking of pulling the whole `oembed` package out to make it its own repo for others to use since the only other `oembed` packages I could find for Go were horribly out of date, but I didn't get quite that far

**Review by yasserfaraazkhan — APPROVED** [review]
