### PR TITLE
[MM-54474]  Fixed behaviour of markdown code button 

### LINKED ISSUE #24532: The code button can break the formatting if the code has valid markdown
#### Summary
Marking selected text as code will render markdown depsite being inside the code tags

#### Steps to reproduce
Write a message like this:
```
Test
====
hello
```
Mark all text and click the "code" button (Ctrl Alt C). That will give you something like this:
````
```Test
====
hello```
````
And send the message

#### Expected behavior
Clicking the code button should produce valid syntax.

#### Observed behavior (that appears unintentional) 
Doing what's described above will produce invalid syntax, as the backticks should have been on their own lines, not just inserted at the beginning of the first line, and on the end of the last line. If the selected text contains valid markdown, it will be rendered, instead of creating a code block.

EDIT: If you do the same steps, but without markdown, it will render inline code on separate lines, not a multiline code block..

I am aware that you could call this a user error, but I still think it's slightly a surprising behaviour.

#### Possible fixes
No suggestion, I'm just a regular user :-)

### PR DESCRIPTION
**Pull request by Paul-vrn**
#### Summary

Modified the `applyMarkdown` function from webapp/channels/src/utils/markdown/apply_markdown.ts to make the code button work correctly as requested by this [comment](https://github.com/mattermost/mattermost/issues/24532#issuecomment-1743272640).

Added new unit tests to apply_markdown.test.ts to test the new behaviour of `applyMarkdown` with code block and inline code.

#### Ticket Link

Fixed #24532 
Jira [https://mattermost.atlassian.net/browse/MM-54474](https://mattermost.atlassian.net/browse/MM-54474)

##### Before:

https://github.com/mattermost/mattermost/assets/78180340/9a51efef-56eb-4cac-ac9c-febca9cdf630

##### After:
https://github.com/mattermost/mattermost/assets/78180340/329694ef-ce6b-431f-b103-fa1e838950b3

#### Release Note

```release-note
Modified behaviour of code button (Ctrl + Alt + C) to create inline code or code block
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
Really nice work, thank you! In order to fix the pipeline I think you just need to sync your branch with master

File: webapp/channels/src/utils/markdown/apply_markdown.ts [hunk 1]
```diff
@@ -492,6 +491,68 @@ export function applyLinkMarkdown({selectionEnd, selectionStart, message, url =
...
 }
 
+function applyCodeMarkdown({selectionEnd, selectionStart, message}: ApplySpecificMarkdownOptions) {
+    if (isSelectionMultiline(message, selectionStart, selectionEnd)) {
+        return applyCodeBlockToSelection({selectionEnd, selectionStart, message});
+    }
+    return applyMarkdownToSelection({selectionEnd, selectionStart, message, delimiter: '`'});
+}
+
+const applyCodeBlockToSelection = ({
```
Comment (hmhealey) [inline webapp/channels/src/utils/markdown/apply_markdown.ts:501]: For this function, is the only difference between this and `applyMarkdownToSelection` that this has separate start and end delimiters?

If so, it'd be nice to not duplicate most of this logic, so could we modify `applyMarkdownToSelection` to support either `delimiter` or `delimiterStart`/`delimiterEnd` as arguments? I think that wouldn't be too hard if you just use this version and set them like `delimiterStart = options.delimiterStart ?? options.delimiter`

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR! This looks great. I just have one suggestion for cleaning up the code slightly

File: webapp/channels/src/utils/markdown/apply_markdown.ts (hunk 1 above)
Comment (Paul-vrn) [reply webapp/channels/src/utils/markdown/apply_markdown.ts:501]: Yes, it's the only difference, I added a new function because of the comment before the switch case:
```
    /**
     * all options that need to be handled in a ver specific way have their own applyMarkdown (sub-)functions.
     * The rest just define their delimiters and return the basic applyMarkdownToSelection function.
     */
```
I'll change the code to only use applyMarkdownToSelection 👍

**Review by hmhealey — APPROVED** [review]
Thanks for changing that. It looks great!

The CI failure that's happening isn't related to this PR. I'll update to the latest master again since that should fix it

**Comment by hmhealey** [comment]
Thanks again for the PR!
