### PR TITLE
[MM-61102] Fix errcheck issues in server/channels/app/channel_bookmark_test.go

### LINKED ISSUE #28782: Fix errcheck issues in server/channels/app/channel_bookmark_test.go
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/app/channel_bookmark_test.go`.

### What is `errcheck`?
`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behaviour. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- Remove the exception for `channels/app/channel_bookmark_test.go` from the exceptions list for `errcheck` in `server/.golangci.yml`.
- Run `make golangci-lint` to get a list of all linter errors.
- Fix the errors by properly handling them.
- Run `make golangci-lint` again to ensure all errors are fixed.

#### Okay, but what does "properly handling" mean?
In general, errors should be returned to the caller. Non critical errors should be loggged, and function execution should continue. There are some exceptions to this rule, such as when the error is expected and should be ignored or when the error is handled in a different way. In such cases, a comment should be added to explain why the error is ignored.

In tests, errors should be checked using `require.NoError(t, err)` for errors of type `error` or `require.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `require.Error(t, err)` for errors of type `error` or `require.NotNil(t, err)` for errors of type `**model.AppError`.

Use `err` as the variable name for errors and `appErr` for `*model.AppError`. Avoid using variable names like `err1`, `err2`, etc. See [the Mattermost style guide](https://developers.mattermost.com/contribute/more-info/server/style-guide/#error-variable-names) for more information.

https://github.com/mattermost/mattermost/pull/28364 and https://github.com/mattermost/mattermost/pull/28376 can be used as examples of how to fix `errcheck` issues in the `api4` package.

-------------

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

If this ticket is already taken, please check out our other [Help Wanted tickets](https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22) of this campaign.

Thank you for your contributions to Mattermost!

----------------

JIRA: MM-61102

### PR DESCRIPTION
**Pull request by RS-labhub**
#### Summary
Fixed the errcheck issues

#### Ticket Link
fixes #28782 
Jira [MM-61102](https://mattermost.atlassian.net/browse/MM-61102)

#### Release Note
```release-note
NONE
```

[MM-61102]: https://mattermost.atlassian.net/browse/MM-61102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: server/channels/app/channel_bookmark_test.go [hunk 1]
```diff
@@ -98,8 +98,13 @@ func TestUpdateBookmark(t *testing.T) {
 			HasPreviewImage: true,
 		}
 
-		th.App.Srv().Store().FileInfo().Save(th.Context, file)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		if _, appErr := th.App.Srv().Store().FileInfo().Save(th.Context, file); appErr != nil {
+			assert.Nil(t, appErr)
+		}
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:103]: We actually don't need the `if` checks.

**Review by hanzei — CHANGES_REQUESTED** [review]
There are still some linter errors. Can you please take a look? Thanks!

```
Error: channels/app/channel_bookmark_test.go:102:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:106:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:130:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:133:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:137:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:282:3: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:286:3: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:377:3: calling require.Nil on error, please use require.NoError instead
```

File: server/channels/app/channel_bookmark_test.go (hunk 1 above)
Comment (RS-labhub) [reply server/channels/app/channel_bookmark_test.go:103]: That was my mistake... sorry for that.. I was shortening the code and forget to remove that. So sorry!

**Comment by RS-labhub** [comment]
@hanzei how to check the linter tests?

File: server/channels/app/channel_bookmark_test.go [hunk 2]
```diff
@@ -102,8 +102,12 @@ func TestUpdateBookmark(t *testing.T) {
 			HasPreviewImage: true,
 		}
 
-		th.App.Srv().Store().FileInfo().Save(th.Context, file)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		_, appErr := th.App.Srv().Store().FileInfo().Save(th.Context, file)
+		assert.NoError(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:106]: Nit: `Save` return an `error`, hence the variable name should be `err` instead of `appErr`

File: server/channels/app/channel_bookmark_test.go [hunk 3]
```diff
@@ -125,9 +129,14 @@ func TestUpdateBookmark(t *testing.T) {
 			HasPreviewImage: true,
 		}
 
-		th.App.Srv().Store().FileInfo().Save(th.Context, file2)
-		th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+		_, appErr = th.App.Srv().Store().FileInfo().Save(th.Context, file2)
+		assert.NoError(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:133]: Same here

File: server/channels/app/channel_bookmark_test.go [hunk 4]
```diff
@@ -125,9 +129,14 @@ func TestUpdateBookmark(t *testing.T) {
...
+		appErr = th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
+		assert.NoError(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:135]: And here

File: server/channels/app/channel_bookmark_test.go [hunk 5]
```diff
@@ -279,7 +293,9 @@ func TestGetChannelBookmarks(t *testing.T) {
 		Emoji:       ":smile:",
 	}
 
-	th.App.CreateChannelBookmark(th.Context, bookmark2, "")
+	if _, appErr := th.App.CreateChannelBookmark(th.Context, bookmark2, ""); appErr != nil {
+		assert.Nil(t, appErr)
+	}
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:298]: We don't need the `if` check

File: server/channels/app/channel_bookmark_test.go [hunk 6]
```diff
@@ -290,7 +306,9 @@ func TestGetChannelBookmarks(t *testing.T) {
 
 	t.Run("get bookmarks of a channel after one is deleted (aka only return the changed bookmarks)", func(t *testing.T) {
 		now := model.GetMillis()
-		th.App.DeleteChannelBookmark(bookmark1.Id, "")
+		if _, appErr := th.App.DeleteChannelBookmark(bookmark1.Id, ""); appErr != nil {
+			assert.Nil(t, appErr)
+		}
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:311]: Same here

File: server/channels/app/channel_bookmark_test.go [hunk 7]
```diff
@@ -437,7 +458,9 @@ func TestUpdateChannelBookmarkSortOrder(t *testing.T) {
 		assert.Equal(t, find_bookmark(bookmarks, bookmark4.Id).SortOrder, int64(4))
 
 		// now reset order
-		th.App.UpdateChannelBookmarkSortOrder(bookmark0.Id, channelId, int64(0), "")
+		if _, appErr = th.App.UpdateChannelBookmarkSortOrder(bookmark0.Id, channelId, int64(0), ""); appErr != nil {
+			assert.Nil(t, appErr)
+		}
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:463]: And here

**Review by hanzei — CHANGES_REQUESTED** [review]
CI is green now :rocket: 

Please take a look at my comments below

**Review by RS-labhub — COMMENTED** [review]
Renamed and removed unnecessary lines

File: server/channels/app/channel_bookmark_test.go [hunk 8]
```diff
@@ -125,9 +129,14 @@ func TestUpdateBookmark(t *testing.T) {
...
+		assert.NoError(t, err)
+		err = th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
+		assert.NoError(t, err)
+		defer func() {
+			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+			assert.NoError(t, err)
+		}()
 
 		bookmark2.FileId = file2.Id
 		bookmarkResp, err = th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:142]: This also needs to be renamed to `*model.AppError`.

File: server/channels/app/channel_bookmark_test.go [hunk 9]
```diff
@@ -102,8 +102,12 @@ func TestUpdateBookmark(t *testing.T) {
...
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		_, err := th.App.Srv().Store().FileInfo().Save(th.Context, file)
+		assert.NoError(t, err)
+		defer func() {
+			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+			assert.NoError(t, err)
+		}()
 
 		bookmark2 := createBookmark("File to be updated", model.ChannelBookmarkFile, th.BasicChannel.Id, file.Id)
 		bookmarkResp, err := th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:113]: We are now getting a conflict between `error` and `*model.AppError`. The clean solution would be to rename this `err` variable to `appErr`.

**Review by hanzei — CHANGES_REQUESTED** [review]
We are getting there!

File: server/channels/app/channel_bookmark_test.go (hunk 8 above)
Comment (RS-labhub) [reply server/channels/app/channel_bookmark_test.go:142]: For this too? https://github.com/mattermost/mattermost/pull/28789#discussion_r1816418394

Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:142]: Yes, this comment in related to https://github.com/mattermost/mattermost/pull/28789#discussion_r1816418394

Comment (RS-labhub) [reply server/channels/app/channel_bookmark_test.go:142]: Fixed!

File: server/channels/app/channel_bookmark_test.go (hunk 9 above)
Comment (RS-labhub) [reply server/channels/app/channel_bookmark_test.go:113]: Done!

**Review by RS-labhub — COMMENTED** [review]
Done!

**Comment by rahimrahman** [comment]
@hanzei I'm going to remove myself as a reviewer.  My understanding of Go is very basic, I appreciate reading the code here.  But I don't feel comfortable giving a proper review and approval. Please assign another reviewer.  Thanks.

**Review by RS-labhub — COMMENTED** [review]
Done

File: server/channels/app/channel_bookmark_test.go (hunk 9 above)
Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:113]: The issue isn't fixed yet. Do you need any help?

**Review by hanzei — CHANGES_REQUESTED** [review]

**Comment by RS-labhub** [comment]
I renamed `err` to `appErr` but I'm not able to see my changes. That's weird. Let me get back to this branch and check it out. As far as I remember, I changed it!

**Comment by RS-labhub** [comment]
> I renamed `err` to `appErr` but I'm not able to see my changes. That's weird. Let me get back to this branch and check it out. As far as I remember, I changed it!

Hey @hanzei I was right, I did the changes:
image

I don't why it's not showing in my pushed commit 🙃

**Comment by RS-labhub** [comment]
Found the error and fixed it!

File: server/channels/app/channel_bookmark_test.go (hunk 9 above)
Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:113]: This is still a concern. See the CI error:

```

=== FAIL: channels/app TestUpdateBookmark/same_user_update_a_channel_bookmark (re-run 1) (0.01s)
    channel_bookmark_test.go:114: 
        	Error Trace:	/mattermost/server/channels/app/channel_bookmark_test.go:114
        	            				/mattermost/server/channels/app/channel_bookmark_test.go:168
        	Error:      	Received unexpected error:
        	            	<nil>
        	Test:       	TestUpdateBookmark/same_user_update_a_channel_bookmark
```

**Review by hanzei — CHANGES_REQUESTED** [review]

**Comment by RS-labhub** [comment]
Now it's fixed for sure!

**Review by hanzei — CHANGES_REQUESTED** [review]
We are getting here

```

Error: channels/app/channel_bookmark_test.go:109:4: calling assert.Nil on error, please use assert.NoError instead
Error: channels/app/channel_bookmark_test.go:138:4: calling assert.Nil on error, please use assert.NoError instead
```

File: server/channels/app/channel_bookmark_test.go (hunk 9 above)
Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:113]: @RS-labhub Do you have any questions regarding the feedback?

**Comment by RS-labhub** [comment]
> We are getting here
> 
> ```
> 
> Error: channels/app/channel_bookmark_test.go:109:4: calling assert.Nil on error, please use assert.NoError instead
> Error: channels/app/channel_bookmark_test.go:138:4: calling assert.Nil on error, please use assert.NoError instead
> ```

If I do `require.NoError` then test case fails, if I do `require.Nil` then test case also fails. 

POV: It's an appErr, therefore it should be `require.Nil`

File: server/channels/app/channel_bookmark_test.go (hunk 9 above)
Comment (RS-labhub) [reply server/channels/app/channel_bookmark_test.go:113]: @hanzei check this: https://github.com/mattermost/mattermost/pull/28789#issuecomment-2468009428

Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:113]: You are missing up the `error` type and the `*model.AppError` type. This line needs to become a new variable as `err` is of type `error`.

File: server/channels/app/channel_bookmark_test.go [hunk 10]
```diff
@@ -102,12 +102,16 @@ func TestUpdateBookmark(t *testing.T) {
...
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		_, err := th.App.Srv().Store().FileInfo().Save(th.Context, file)
+		assert.NoError(t, err)
+		defer func() {
+			appErr := th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+			assert.Nil(t, appErr)
+		}()
 
 		bookmark2 := createBookmark("File to be updated", model.ChannelBookmarkFile, th.BasicChannel.Id, file.Id)
 		bookmarkResp, err := th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:113]:
```suggestion
		bookmark2 := createBookmark("File to be updated", model.ChannelBookmarkFile, th.BasicChannel.Id, file.Id)
		bookmarkResp, appErr := th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```

File: server/channels/app/channel_bookmark_test.go [hunk 11]
```diff
@@ -102,12 +102,16 @@ func TestUpdateBookmark(t *testing.T) {
...
-		require.Nil(t, err)
+		require.NoError(t, err)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:114]:
```suggestion
		require.Nil(t, appErr)
```

File: server/channels/app/channel_bookmark_test.go [hunk 12]
```diff
@@ -102,12 +102,16 @@ func TestUpdateBookmark(t *testing.T) {
 			HasPreviewImage: true,
 		}
 
-		th.App.Srv().Store().FileInfo().Save(th.Context, file)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		_, err := th.App.Srv().Store().FileInfo().Save(th.Context, file)
+		assert.NoError(t, err)
+		defer func() {
+			appErr := th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+			assert.Nil(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:109]: This is an an `error`
```suggestion
			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
			assert.NoError(t, err)
```

**Review by hanzei — CHANGES_REQUESTED** [review]

**Comment by RS-labhub** [comment]
I hope it's all good now!

File: server/channels/app/channel_bookmark_test.go [hunk 13]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
-		th.App.Srv().Store().FileInfo().Save(th.Context, file2)
-		th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+		_, err = th.App.Srv().Store().FileInfo().Save(th.Context, file2)
+		assert.NoError(t, err)
+		err = th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
+		assert.NoError(t, err)
+		defer func() {
+			appErr := th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+			assert.Nil(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:138]: It is getting better! Now this also needs to become an `err` (and `require.NoError` should be used)

File: server/channels/app/channel_bookmark_test.go (hunk 8 above)
Comment (hanzei) [reply server/channels/app/channel_bookmark_test.go:142]: Sorry, this is still unresolved.

File: server/channels/app/channel_bookmark_test.go [hunk 14]
```diff
@@ -353,7 +369,10 @@ func TestUpdateChannelBookmarkSortOrder(t *testing.T) {
 
 	_, err := th.App.Srv().Store().FileInfo().Save(th.Context, file)
 	require.NoError(t, err)
-	defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+	defer func() {
+		err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file.Id)
+		require.Nil(t, err)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:374]:
```suggestion
		require.NoError(t, err)
```

**Review by hanzei — CHANGES_REQUESTED** [review]
It is getting better! :tada:

**Comment by RS-labhub** [comment]
I messed up everything!! I hope it's good now 😑

Extremely Sorry for messing this PR

File: server/channels/app/channel_bookmark_test.go [hunk 15]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
 
-		th.App.Srv().Store().FileInfo().Save(th.Context, file2)
-		th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
-		defer th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+		_, err = th.App.Srv().Store().FileInfo().Save(th.Context, file2)
+		assert.NoError(t, err)
+		err = th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
+		assert.NoError(t, err)
+		defer func() {
+			err := th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:137]: Let's re-use the `err` variable
```suggestion
			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
```

File: server/channels/app/channel_bookmark_test.go [hunk 16]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
+		assert.NoError(t, err)
+		err = th.App.Srv().Store().FileInfo().AttachToPost(th.Context, file2.Id, model.NewId(), th.BasicChannel.Id, model.BookmarkFileOwner)
+		assert.NoError(t, err)
+		defer func() {
+			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+			require.NoError(t, err)
+		}()
 
 		bookmark2.FileId = file2.Id
 		bookmarkResp, err = th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:142]:
```suggestion
		bookmarkResp, appErr := th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```

File: server/channels/app/channel_bookmark_test.go [hunk 17]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
-		require.NotNil(t, err)
+		require.Error(t, err)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:143]:
```suggestion
		require.Nil(t, appErr)
```

File: server/channels/app/channel_bookmark_test.go [hunk 18]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
+		assert.NoError(t, err)
+		defer func() {
+			err = th.App.Srv().Store().FileInfo().PermanentDelete(th.Context, file2.Id)
+			require.NoError(t, err)
+		}()
 
 		bookmark2.FileId = file2.Id
-		bookmarkResp, err = th.App.CreateChannelBookmark(th.Context, bookmark2, "")
-		require.NotNil(t, err)
+		bookmarkResp, appErr := th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:142]:
```suggestion
		bookmarkResp, appErr = th.App.CreateChannelBookmark(th.Context, bookmark2, "")
```

File: server/channels/app/channel_bookmark_test.go [hunk 19]
```diff
@@ -125,13 +129,18 @@ func TestUpdateBookmark(t *testing.T) {
...
+		require.Nil(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_bookmark_test.go:143]:
```suggestion
		require.NotNil(t, appErr)
```

**Comment by RS-labhub** [comment]
@hanzei @gabrieljackson all checks are passed now. Finally merging time!

**Review by hanzei — APPROVED** [review]
Finally :rocket:

**Review by gabrieljackson — APPROVED** [review]
LGTM
