### PR TITLE
[MM 22957] webapp a11y: fix sso btns focus issue

### LINKED ISSUE #22957: webapp a11y: sso login button not keyboard activatable
#### Summary

The SSO login process is not accessible with the keyboard.  Using the keyboard to navigate to the SSO button, then pressing enter to activate it, results in the email/password form being submitted instead.

#### Steps to reproduce

- Visit the login page of a mattermost webapp: https://community-daily.mattermost.com/login
- Use the keyboard tabbing to navigate to the SSO button (Okta in the mattermost instance above)
- Press enter

#### Expected behavior

The button/url is activitated and I'm redirected to the SSO provider login.

#### Observed behavior (that appears unintentional) 

I see an error ("Please enter your email or username"), and I'm not redirected to the SSO provider login.  See screenshot:

### PR DESCRIPTION
**Pull request by saideepesh000**
#### Summary

This PR fixes the ally issue of sso buttons on login page

#### Ticket Link

fixes #22957 

#### Screenshots

https://user-images.githubusercontent.com/43727167/236675329-475702c3-80e0-4158-823b-ab1b386ff6a1.mov

#### Release Note

```release-note
[MM 22957] webapp a11y: fix sso btns focus issue
```

### CODE REVIEW

File: webapp/channels/src/components/external_login_button/external_login_button.tsx [hunk 1]
```diff
@@ -1,18 +1,21 @@
 // Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
 // See LICENSE.txt for license information.
 
-import React from 'react';
+import React, {FocusEventHandler} from 'react';
 import classNames from 'classnames';
 
 import './external_login_button.scss';
 
+
```
Comment (pvev) [inline webapp/channels/src/components/external_login_button/external_login_button.tsx:9]: unnecessary blank line, please remove

File: webapp/channels/src/components/external_login_button/external_login_button.tsx [hunk 2]
```diff
@@ -22,12 +25,17 @@ const ExternalLoginButton = ({
...
+    onBlur
 }: ExternalLoginButtonType) => (
     <a
         id={id}
         className={classNames('external-login-button', {'direction-column': direction === 'column'}, id)}
         href={url}
         style={style}
+        onFocus={onFocus}
+        onBlur={onBlur}
+
```
Comment (pvev) [inline webapp/channels/src/components/external_login_button/external_login_button.tsx:38]: unnecessary blank line, please remove

File: webapp/channels/src/components/login/login.tsx [hunk 3]
```diff
@@ -121,6 +121,8 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
     const [alertBanner, setAlertBanner] = useState<AlertBannerProps | null>(null);
     const [hasError, setHasError] = useState(false);
     const [isMobileView, setIsMobileView] = useState(false);
+    const [isExternalBtnFocused, setIsExternalBtnFocused] = useState<boolean>(false);
+
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:125]: unnecessary blank line, please remove

File: webapp/channels/src/components/login/login.tsx [hunk 4]
```diff
@@ -129,22 +131,31 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
     const enableSignInWithEmail = EnableSignInWithEmail === 'true';
     const enableSignInWithUsername = EnableSignInWithUsername === 'true';
     const enableSignUpWithEmail = EnableSignUpWithEmail === 'true';
-    const enableSignUpWithGitLab = EnableSignUpWithGitLab === 'true';
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:132]: This logic needs to remain the way it was before, we can not assign this logic to `true` directly. We need to check if that config value is actually enabled.

File: webapp/channels/src/components/login/login.tsx [hunk 5]
```diff
@@ -129,22 +131,31 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
...
+    const enableSignUpWithOffice365 = true;
+    const enableSignUpWithOpenId = true;
     const isLicensed = IsLicensed === 'true';
     const ldapEnabled = isLicensed && enableLdap;
     const enableSignUpWithSaml = isLicensed && enableSaml;
     const siteName = SiteName ?? '';
 
     const enableBaseLogin = enableSignInWithEmail || enableSignInWithUsername || ldapEnabled;
-    const enableExternalSignup = enableSignUpWithGitLab || enableSignUpWithOffice365 || enableSignUpWithGoogle || enableSignUpWithOpenId || enableSignUpWithSaml;
+    const enableExternalSignup = true;
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:144]: same here, we can not hardcode this directly to `true`

File: webapp/channels/src/components/login/login.tsx [hunk 6]
```diff
@@ -674,7 +685,9 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
 
     const onEnterKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
         if (e.key === Constants.KeyCodes.ENTER[0]) {
-            preSubmit(e);
+            if(!isExternalBtnFocused){
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:688]: shouldn't this be a positive evaluation? I mean, the check should be `if (isExternalBtnFocused)`

File: webapp/channels/src/components/login/login.tsx [hunk 7]
```diff
@@ -827,11 +840,13 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
                                     </span>
                                 </div>
                             )}
-                            {enableExternalSignup && (
+                            {true && (
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:843]: this condition must remain as it was before. It doesn't make any sense to hardcode a bool value in a condition.

File: webapp/channels/src/components/login/login.tsx [hunk 8]
```diff
@@ -129,22 +131,31 @@ const Login = ({onCustomizeHeader}: LoginProps) => {
...
 
     const enableBaseLogin = enableSignInWithEmail || enableSignInWithUsername || ldapEnabled;
-    const enableExternalSignup = enableSignUpWithGitLab || enableSignUpWithOffice365 || enableSignUpWithGoogle || enableSignUpWithOpenId || enableSignUpWithSaml;
+    const enableExternalSignup = true;
     const showSignup = enableOpenServer && (enableExternalSignup || enableSignUpWithEmail || enableLdap);
 
     const query = new URLSearchParams(search);
     const redirectTo = query.get('redirect_to');
 
+    const handleExternalBtnFocus = () => {
```
Comment (pvev) [inline webapp/channels/src/components/login/login.tsx:150]: you can simplify this to be only one function and then use it this way:

```
const handleExternalBtnFocusBlur = (isFocused: boolean) => {
    setIsExternalBtnFocused(isFocused)
}

```

And then use it like this:

```
<ExternalLoginButton
    ...
    onFocus={() => handleExternalBtnFocusBlur(true)}
    onBlur={() => handleExternalBtnFocusBlur(false)}
    ...
/>
```

also, the function should be memoized using the useCallback function to avoid unnecessary re-renders of the child component.

**Review by pvev — CHANGES_REQUESTED** [review]
Thank you for your contribution @saideepesh000 , the solution you propose seems like a right approach to me. I have requested some changes before approving. Please address those and let me know if you have any questions or need any help or guidance. Thanks!

File: webapp/channels/src/components/login/login.tsx (hunk 4 above)
Comment (saideepesh000) [reply webapp/channels/src/components/login/login.tsx:132]: damn, sorry my bad, should've check this before raising the PR

File: webapp/channels/src/components/login/login.tsx (hunk 5 above)
Comment (saideepesh000) [reply webapp/channels/src/components/login/login.tsx:144]: sorry, my bad, did this for testing, forgot to revert, should've done before raising PR

**Comment by saideepesh000** [comment]
> Thank you for your contribution @saideepesh000 , the solution you propose seems like a right approach to me. I have requested some changes before approving. Please address those and let me know if you have any questions or need any help or guidance. Thanks!

thanks @pvev, addressed the comments

**Review by pvev — CHANGES_REQUESTED** [review]
thanks for the quick fix to my previous change requests 🚀  @saideepesh000 . Please review my latests comments. Thanks!

**Comment by saideepesh000** [comment]
> thanks for the quick fix to my previous change requests 🚀 @saideepesh000 . Please review my latests comments. Thanks!

@pvev done 🚀

File: webapp/channels/src/components/external_login_button/external_login_button.tsx (hunk 2 above)
Comment (pvev) [reply webapp/channels/src/components/external_login_button/external_login_button.tsx]: not sure why is not getting fixed, it not a blocker but is a good practice to not add unnecessary lines, specially before closing tags.

**Comment by hmhealey** [comment]
Sorry for barging in a bit, but if I could actually suggest a different fix here, we don't actually need a key handler or to track focus here if we just wrap the login fields in an HTML form. A form's `submit` event will trigger whenever the user presses enter while their focus is in the form or whenever they click on a submit button (like `SaveButton` uses internally). It just looks like:
```jsx
const preSubmit = (e) => {
    e.preventDefault(); // This is important since the default browser behaviour is to make a request and reload the page

    // And so on
};

return (
    <form onSubmit={preSubmit}>
        <input id='username'/>
        <button type='submit'>{'Save'}</button>
    </form>
);
```
It also won't interfere with any other non-submit buttons in the form as well. Currently, the "Forgot your password" link and the "show password" toggle also have the same issue as the SSO buttons, but they should work just fine even if they're inside a form

**Comment by saideepesh000** [comment]
@hmhealey made the changes, please check it.

**Review by BenCookie95 — APPROVED** [review]
LGTM! Tested locally

**Review by hmhealey — APPROVED** [review]
Thanks for redoing that, @saideepesh000. I'm glad it worked how I remembered since I've only actually used `form`s a couple times. I wonder if there's other places in the app that we could use that pattern to fix similar issues too...

**Review by yasserfaraazkhan — APPROVED** [review]
