### PR TITLE
Fix: Add aria-label to Create Team button to improve screen reader accessibility 

### LINKED ISSUE #26483: Screen reader: Add team button in team sidebar doesn't read out proper label
### Steps to reproduce

- With screen reader on (ideally JAWS)
- Click on the top of the team sidebar in Mattermost to place focus in that region
- `TAB` until you get to the + button within the team sidebar (note: you must have access to create teams)

### Observed

- Customer reported that the screen reader reads out ‘team unread link’ 
- This was confusing and didn’t make a lot of sense

### Expected

- The screen reader should read out “Create a team” or “Other teams you can join” as the tooltip states when you hover

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-55284

### PR DESCRIPTION
**Pull request by Student-coder-web**
This PR adds an aria-label to the Create Team ("+") button in the team sidebar.

Screen readers previously announced it as “team unread link”, which was unclear.
Now it correctly reads “Create a team”, improving accessibility for visually impaired users.
#### Release Note
```release-note
NONE
```

Fixes #26483

### CODE REVIEW

File: webapp/channels/src/components/team_sidebar/components/team_button.tsx [hunk 1]
```diff
@@ -94,15 +94,19 @@ export default function TeamButton({
...
-        ariaLabel = formatMessage({
-            id: 'team.button.unread.ariaLabel',
-            defaultMessage: '{teamName} team unread',
-        },
-        {
-            teamName: displayName,
-        });
-
-        if (mentions) {
+
```
Comment (pvev) [inline webapp/channels/src/components/team_sidebar/components/team_button.tsx]: please, fix this whitespace issue

**Review by pvev — APPROVED** [review]
thanks @Student-coder-web , I am approving but with a request if you want to add a unit test covering this? actually to cover correctly the logic, we would like to cover with unit tests that it sets correctly the aria-label for the create team button, for the unread team case and for the team with mentions, that would be ideal.

File: webapp/channels/src/components/team_sidebar/components/team_button.tsx (hunk 1 above)
Comment (ajay-kumbhar01) [reply webapp/channels/src/components/team_sidebar/components/team_button.tsx]: The issue is resolved. Let me know if anything else is needed.

**Comment by ajay-kumbhar01** [comment]
Hi @hmhealey, I have pushed the requested unit tests.  
Please let me know if any more changes are needed.

**Review by yasserfaraazkhan — APPROVED** [review]
