### PR TITLE
[MM-61101] Fix errcheck issues in server/channels/app/channel.go

### LINKED ISSUE #28781: Fix errcheck issues in server/channels/app/channel.go
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/app/channel.go`.

### What is `errcheck`?
`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behaviour. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- Remove the exception for `channels/app/channel.go` from the exceptions list for `errcheck` in `server/.golangci.yml`.
- Run `make golangci-lint` to get a list of all linter errors.
- Fix the errors by properly handling them.
- Run `make golangci-lint` again to ensure all errors are fixed.

#### Okay, but what does "properly handling" mean?
In general, errors should be returned to the caller. Non critical errors should be loggged, and function execution should continue. There are some exceptions to this rule, such as when the error is expected and should be ignored or when the error is handled in a different way. In such cases, a comment should be added to explain why the error is ignored.

In tests, errors should be checked using `require.NoError(t, err)` for errors of type `error` or `require.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `require.Error(t, err)` for errors of type `error` or `require.NotNil(t, err)` for errors of type `**model.AppError`.

Use `err` as the variable name for errors and `appErr` for `*model.AppError`. Avoid using variable names like `err1`, `err2`, etc. See [the Mattermost style guide](https://developers.mattermost.com/contribute/more-info/server/style-guide/#error-variable-names) for more information.

https://github.com/mattermost/mattermost/pull/28364 and https://github.com/mattermost/mattermost/pull/28376 can be used as examples of how to fix `errcheck` issues in the `api4` package.

-------------

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

If this ticket is already taken, please check out our other [Help Wanted tickets](https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22) of this campaign.

Thank you for your contributions to Mattermost!

----------------

JIRA: MM-61101

### PR DESCRIPTION
**Pull request by RS-labhub**
#### Summary
Fixed the errcheck issues

#### Ticket Link
fixes #28781 
Jira [MM-61101](https://mattermost.atlassian.net/browse/MM-61101)

#### Release Note
```release-note
NONE
```

[MM-61101]: https://mattermost.atlassian.net/browse/MM-61101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

File: server/channels/app/channel.go [hunk 1]
```diff
@@ -705,7 +707,9 @@ func (a *App) UpdateChannelPrivacy(c request.CTX, oldChannel *model.Channel, use
 			channel.Type = model.ChannelTypeOpen
 		}
 		// revert to previous channel privacy
-		a.UpdateChannel(c, channel)
+		if _, err = a.UpdateChannel(c, channel); err != nil {
+			return nil, err
+		}
```
Comment (streamer45) [inline server/channels/app/channel.go:712]: This being already an error case (`postChannelPrivacyMessage` has failed), we could be losing useful information. I'd probably consider wrapping both errors. @hanzei thoughts?

Comment (hanzei) [reply server/channels/app/channel.go:712]: If there is a way to warp both errors into one ` *model.AppError`, I'm fully supportive.  Otherwise, we can just log this error and return the one from `postChannelPrivacyMessage`.

Comment (RS-labhub) [reply server/channels/app/channel.go:712]: Any conclusion?

Comment (hanzei) [reply server/channels/app/channel.go:712]: I think we should just log the error from `UpdateChannel`.  That is the way we do in the rest of the code base, when we need to revert to a state.

Comment (RS-labhub) [reply server/channels/app/channel.go:712]: I lost this branch! 🙃

Comment (hanzei) [reply server/channels/app/channel.go:724]: Did you lose the branch on your local machine? No, problem, you can still fetch it from GitHub. See https://github.com/RS-labhub/mattermost/tree/channel

**Review by hanzei — CHANGES_REQUESTED** [review]

File: server/channels/app/channel.go [hunk 2]
```diff
@@ -717,7 +719,9 @@ func (a *App) UpdateChannelPrivacy(c request.CTX, oldChannel *model.Channel, use
 			channel.Type = model.ChannelTypeOpen
 		}
 		// revert to previous channel privacy
-		a.UpdateChannel(c, channel)
+		if _, err = a.UpdateChannel(c, channel); err != nil {
+			a.Log().Error("Failed to revert channel privacy", mlog.Err(err))
+		}
 		return channel, err
```
[the remark this answers is not in the document]
Comment (RS-labhub) [reply server/channels/app/channel.go:725]: So, shall I revert the changes and do it for `postChannelPrivacyMessage`

[the remark this answers is not in the document]
Comment (RS-labhub) [reply server/channels/app/channel.go:725]: You mean we need to log the error messages present here?

```go
func (a *App) postChannelPrivacyMessage(c request.CTX, user *model.User, channel *model.Channel) *model.AppError {
	var authorId string
	var authorUsername string
	if user != nil {
		authorId = user.Id
		authorUsername = user.Username
	} else {
		systemBot, err := a.GetSystemBot(c)
		if err != nil {
			return model.NewAppError("postChannelPrivacyMessage", "api.channel.post_channel_privacy_message.error", nil, "", http.StatusInternalServerError).Wrap(err)
		}

		authorId = systemBot.UserId
		authorUsername = systemBot.Username
	}

	message := (map[model.ChannelType]string{
		model.ChannelTypeOpen:    i18n.T("api.channel.change_channel_privacy.private_to_public"),
		model.ChannelTypePrivate: i18n.T("api.channel.change_channel_privacy.public_to_private"),
	})[channel.Type]
	post := &model.Post{
		ChannelId: channel.Id,
		Message:   message,
		Type:      model.PostTypeChangeChannelPrivacy,
		UserId:    authorId,
		Props: model.StringInterface{
			"username": authorUsername,
		},
	}

	if _, err := a.CreatePost(c, post, channel, model.CreatePostFlags{SetOnline: true}); err != nil {
		return model.NewAppError("postChannelPrivacyMessage", "api.channel.post_channel_privacy_message.error", nil, "", http.StatusInternalServerError).Wrap(err)
	}

	return nil
}
```

[the remark this answers is not in the document]
Comment (RS-labhub) [reply server/channels/app/channel.go]: I hope the new update makes sense

**Review by hanzei — APPROVED** [review]
There is one issue with the diff. 

Otherwise LGTM :+1:

**Comment by RS-labhub** [comment]
Done!
