### PR TITLE
Fixed errcheck issues in server/channels/app/channel_test.go

### LINKED ISSUE #28784: Fix errcheck issues in server/channels/app/channel_test.go
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/app/channel_test.go`.

### What is `errcheck`?
`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behaviour. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- Remove the exception for `channels/app/channel_test.go` from the exceptions list for `errcheck` in `server/.golangci.yml`.
- Run `make golangci-lint` to get a list of all linter errors.
- Fix the errors by properly handling them.
- Run `make golangci-lint` again to ensure all errors are fixed.

#### Okay, but what does "properly handling" mean?
In general, errors should be returned to the caller. Non critical errors should be loggged, and function execution should continue. There are some exceptions to this rule, such as when the error is expected and should be ignored or when the error is handled in a different way. In such cases, a comment should be added to explain why the error is ignored.

In tests, errors should be checked using `require.NoError(t, err)` for errors of type `error` or `require.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `require.Error(t, err)` for errors of type `error` or `require.NotNil(t, err)` for errors of type `**model.AppError`.

Use `err` as the variable name for errors and `appErr` for `*model.AppError`. Avoid using variable names like `err1`, `err2`, etc. See [the Mattermost style guide](https://developers.mattermost.com/contribute/more-info/server/style-guide/#error-variable-names) for more information.

https://github.com/mattermost/mattermost/pull/28364 and https://github.com/mattermost/mattermost/pull/28376 can be used as examples of how to fix `errcheck` issues in the `api4` package.

-------------

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

If this ticket is already taken, please check out our other [Help Wanted tickets](https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22) of this campaign.

Thank you for your contributions to Mattermost!

----------------

JIRA: MM-61104

### PR DESCRIPTION
**Pull request by edlerd**
#### Summary

Fixed errcheck issues in server/channels/app/channel_test.go

#### Ticket Link

Fixes #28784

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the PR! 

Could you please take a look at the linter issues?

```
Error: channels/app/channel_test.go:1838:2: calling require.Nil on error, please use require.NoError instead
Error: channels/app/channel_test.go:2229:5: calling require.Nil on error, please use require.NoError instead
Error: channels/app/channel_test.go:2259:5: calling require.Nil on error, please use require.NoError instead
Error: channels/app/channel_test.go:2261:5: calling require.Nil on error, please use require.NoError instead
Error: channels/app/channel_test.go:2268:5: calling require.Nil on error, please use require.NoError instead
Error: channels/app/channel_test.go:2270:5: calling require.Nil on error, please use require.NoError instead
```

Thanks!

**Comment by edlerd** [comment]
Updated those issue and ensured `make vet` passes locally. Please have another look at this and :crossed_fingers: now it passes CI and review.

**Comment by edlerd** [comment]
Suspect the reuse of the err object in the anonymous defered functions caused the panic. giving them a dedicated name and new object to avoid this.

File: server/channels/app/channel_test.go [hunk 1]
```diff
@@ -59,7 +64,10 @@ func TestPermanentDeleteChannel(t *testing.T) {
 		CallbackURLs: []string{"http://foo"},
 	})
 	require.Nil(t, err)
-	defer th.App.DeleteOutgoingWebhook(outgoing.Id)
+	defer func() {
+		deferErr := th.App.DeleteOutgoingWebhook(outgoing.Id)
+		require.Nil(t, deferErr)
+	}()
```
Comment (hanzei) [inline server/channels/app/channel_test.go:70]: This is throwing a NPE. Can you please take a look? Thanks!

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25d44a5]

goroutine 57576 [running]:
testing.tRunner.func1.2({0x2aff1c0, 0x535c370})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x2aff1c0?, 0x535c370?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/mattermost/mattermost/server/v8/channels/app.TestPermanentDeleteChannel.func3()
	/mattermost/server/channels/app/channel_test.go:52 +0x25
panic({0x2aff1c0?, 0x535c370?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/mattermost/mattermost/server/v8/channels/app.TestPermanentDeleteChannel.func4()
	/mattermost/server/channels/app/channel_test.go:68 +0x25
github.com/mattermost/mattermost/server/v8/channels/app.TestPermanentDeleteChannel(0xc004c6ad00)
	/mattermost/server/channels/app/channel_test.go:86 +0x891
testing.tRunner(0xc004c6ad00, 0x3119490)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
```

**Review by hanzei — CHANGES_REQUESTED** [review]

File: server/channels/app/channel_test.go (hunk 1 above)
Comment (edlerd) [reply server/channels/app/channel_test.go]: This was a tricky one.

Introducing the anonymous function for deferring, lead to `outgoing.Id` being null. Because `defer` without anonymous function wrapper puts the call on the stack with the current value of `outgoing.Id` at the moment of the `defer` being defined. Now with the wrapper `outgoing.Id` is evaluated at a later point, so we have to introduce a temp variable to hold the value for us.

**Comment by edlerd** [comment]
Finally this should be resolved and pass CI 🤞  at least locally I could reproduce, and it is passing now.

**Comment by edlerd** [comment]
Ensured all test cases and make vet passes locally.

File: server/channels/app/channel_test.go [hunk 2]
```diff
@@ -1162,22 +1215,29 @@ func TestGetChannelMembersTimezones(t *testing.T) {
...
+	require.Nil(t, appErr)
 
 	user3 := model.User{Email: strings.ToLower(model.NewId()) + "success+test@example.com", Nickname: "Darth Vader", Username: "vader" + model.NewId(), Password: "passwd1", AuthService: ""}
-	ruser, _ := th.App.CreateUser(th.Context, &user3)
-	th.App.AddUserToChannel(th.Context, ruser, th.BasicChannel, false)
+	ruser, appErr := th.App.CreateUser(th.Context, &user3)
+	require.Nil(t, appErr)
+
+	_, appErr = th.App.AddUserToChannel(th.Context, ruser, th.BasicChannel, false)
+	require.Nil(t, appErr)
```
Comment (hanzei) [inline server/channels/app/channel_test.go:1231]: This errors:
```
    channel_test.go:1231: 
        	Error Trace:	/mattermost/server/channels/app/channel_test.go:1231
        	Error:      	Expected nil, but got: &model.AppError{Id:"app.team.get_member.missing.app_error", Message:"No team member found for that user ID and team ID.", DetailedError:"", RequestId:"", StatusCode:404, Where:"AddUserToChannel", SkipTranslation:false, params:map[string]interface {}(nil), wrapped:(*store.ErrNotFound)(0xc003a0bbf0)}
        	Test:       	TestGetChannelMembersTimezones
```

Which, I think, is correct. The user needs to be added to the team first. Could you please update the code?

File: server/channels/app/channel_test.go [hunk 3]
```diff
@@ -1162,22 +1215,29 @@ func TestGetChannelMembersTimezones(t *testing.T) {
...
 
 	ruser.Timezone["automaticTimezone"] = "NoWhere/Island"
-	th.App.UpdateUser(th.Context, ruser, false)
+	_, appErr = th.App.UpdateUser(th.Context, ruser, false)
+	require.Nil(t, appErr)
 
 	user4 := model.User{Email: strings.ToLower(model.NewId()) + "success+test@example.com", Nickname: "Darth Vader", Username: "vader" + model.NewId(), Password: "passwd1", AuthService: ""}
 	ruser, _ = th.App.CreateUser(th.Context, &user4)
-	th.App.AddUserToChannel(th.Context, ruser, th.BasicChannel, false)
+	_, appErr = th.App.AddUserToChannel(th.Context, ruser, th.BasicChannel, false)
```
Comment (hanzei) [inline server/channels/app/channel_test.go:1239]: Same here, right?

**Review by hanzei — CHANGES_REQUESTED** [review]

File: server/channels/app/channel_test.go [hunk 4]
```diff
@@ -40,13 +40,19 @@ func TestPermanentDeleteChannel(t *testing.T) {
...
 	incoming, err := th.App.CreateIncomingWebhookForChannel(th.BasicUser.Id, channel, &model.IncomingWebhook{ChannelId: channel.Id})
 	require.NotNil(t, incoming, "incoming webhook should not be nil")
 	require.Nil(t, err, "Unable to create Incoming Webhook for Channel")
-	defer th.App.DeleteIncomingWebhook(incoming.Id)
+
+	cleanHookId := incoming.Id
+	defer func() {
+		deferErr := th.App.DeleteIncomingWebhook(cleanHookId)
+		require.Nil(t, deferErr)
+	}()
```
Comment (hanzei) [inline server/channels/app/channel_test.go:55]: Thanks for finding the root cause:+1: 

That is one option. Alternatively, you can add an argument to the function and pass the ID. 
```suggestion
	defer func(hookID string) {
		deferErr := th.App.DeleteIncomingWebhook(hookID)
		require.Nil(t, deferErr)
	}(incoming.Id)
```

File: server/channels/app/channel_test.go [hunk 5]
```diff
@@ -269,17 +294,18 @@ func TestJoinDefaultChannelsCreatesChannelMemberHistoryRecordTownSquare(t *testi
 	th := Setup(t).InitBasic()
 	defer th.TearDown()
 
-	// figure out the initial number of users in town square
+	// figure out the initial number of testUsers in town square
```
Comment (hanzei) [inline server/channels/app/channel_test.go:297]: That doesn't seem correct. `users` is a fine term.

File: server/channels/app/channel_test.go [hunk 6]
```diff
@@ -269,17 +294,18 @@ func TestJoinDefaultChannelsCreatesChannelMemberHistoryRecordTownSquare(t *testi
...
 	channel, err := th.App.Srv().Store().Channel().GetByName(th.BasicTeam.Id, "town-square", true)
 	require.NoError(t, err)
 	townSquareChannelID := channel.Id
-	users, nErr := th.App.Srv().Store().ChannelMemberHistory().GetUsersInChannelDuring(model.GetMillis()-100, model.GetMillis()+100, townSquareChannelID)
+	testUsers, nErr := th.App.Srv().Store().ChannelMemberHistory().GetUsersInChannelDuring(model.GetMillis()-100, model.GetMillis()+100, townSquareChannelID)
 	require.NoError(t, nErr)
-	initialNumTownSquareUsers := len(users)
+	initialNumTownSquareUsers := len(testUsers)
```
Comment (hanzei) [inline server/channels/app/channel_test.go:303]: Please remove the unrelated change

File: server/channels/app/channel_test.go [hunk 7]
```diff
@@ -332,21 +359,25 @@ func TestJoinDefaultChannelsExperimentalDefaultChannels(t *testing.T) {
...
 	for _, channelName := range defaultChannelList {
-		channel, err := th.App.GetChannelByName(th.Context, channelName, th.BasicTeam.Id, false)
-		require.Nil(t, err, "Expected nil, didn't receive nil")
+		channel, appErr := th.App.GetChannelByName(th.Context, channelName, th.BasicTeam.Id, false)
+		require.Nil(t, appErr, "Expected nil, didn't receive nil")
 
-		member, err := th.App.GetChannelMember(th.Context, channel.Id, user.Id)
+		member, appErr := th.App.GetChannelMember(th.Context, channel.Id, user.Id)
 
+		require.Nil(t, appErr, "Expected nil object, didn't receive nil")
```
Comment (hanzei) [inline server/channels/app/channel_test.go:379]: Nit:
```suggestion
		member, appErr := th.App.GetChannelMember(th.Context, channel.Id, user.Id)
		require.Nil(t, appErr, "Expected nil object, didn't receive nil")
```

**Review by hanzei — CHANGES_REQUESTED** [review]
Amazing work @edlerd :tada:

File: server/channels/app/channel_test.go (hunk 5 above)
Comment (edlerd) [reply server/channels/app/channel_test.go:297]: My IDE was complaining this is clashing with the imported users package. Though both `make golangci-lint` and `make vet` are happy with, so I'll revert this.

File: server/channels/app/channel_test.go (hunk 2 above)
Comment (edlerd) [reply server/channels/app/channel_test.go:1232]: I changed the check previously to expect the error, now adjusted the logic to add the user to the team first.

**Comment by edlerd** [comment]
This is ready for another review.

**Comment by edlerd** [comment]
@hanzei everything passes except enterprise tests, which I can't access. is it even related to the changes in here? Maybe this can merge as is?

**Comment by edlerd** [comment]
@hanzei everything passing, can this be merged?

**Review by hanzei — APPROVED** [review]
LGTM, great work :tada:

**Review by isacikgoz — APPROVED** [review]
LGTM, thanks both @edlerd and @hanzei 🚀
