### PR TITLE
MM-53945: Server logs page has shows incorrect message "No channels found"

### LINKED ISSUE #24269: Server logs page has shows incorrect message "No channels found"
In the server logs page, if there are no logs that match the search query, the message displayed says "No channels found", when it should probably say something like "No logs found"

[mattermost/mattermost/webapp/channels/src/components/admin_console/server_logs/log_list.tsx](https://github.com/mattermost/mattermost/blob/700029ccdc04e3f926d65b9cd07000fea0af2749/webapp/channels/src/components/admin_console/server_logs/log_list.tsx#L270-L275)
```tsx
        const placeholderEmpty: JSX.Element = (
            <FormattedMessage
                id='admin.channel_settings.channel_list.no_channels_found'
                defaultMessage='No channels found'
            />
        );
```

_Issue created from a [message in Mattermost](https://community.mattermost.com/core/pl/9riyu4fn8tyiim63crw8wyfu4o)_.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-53945

### PR DESCRIPTION
**Pull request by AsisRout**
#### Summary

This PR is for updating the incorrect log message in server logs page

#### Ticket Link
 

Fixes #24269 
JIRA: https://mattermost.atlassian.net/browse/MM-53945

#### Screenshots

NA

#### Release Note

```release-note
NONE
```

### CODE REVIEW

File: webapp/channels/src/components/admin_console/server_logs/log_list.tsx [hunk 1]
```diff
@@ -270,7 +270,7 @@ export default class LogList extends React.PureComponent<Props, State> {
         const placeholderEmpty: JSX.Element = (
             <FormattedMessage
                 id='admin.channel_settings.channel_list.no_channels_found'
```
Comment (sinansonmez) [inline webapp/channels/src/components/admin_console/server_logs/log_list.tsx:272]: Unfortunately, this is not enough to accomplish the expected behaviour. 
This changes only the default message in case of translation is not found. You need to add a new value like `"admin.channel_settings.channel_list.no_logs_found": "No logs found",` in https://github.com/mattermost/mattermost/blob/bc11b298073033bcf9563ab1461d4000b9873e9e/webapp/channels/src/i18n/en.json. After that you can replace the `id` and `defaultMessage` like 

```suggestion
                id='admin.channel_settings.channel_list.no_logs_found'
```

After your changes dont forget to run `npm run i18n-extract` in `mattermost/webapp/channels` to properly order the new added translation.

**Review by sinansonmez — CHANGES_REQUESTED** [review]

**Comment by AsisRout** [comment]
Fixed..Can you please take a look

**Comment by AsisRout** [comment]
@sinansonmez @M-ZubairAhmed Can you please let me know if there's anything else i need to add for fixing this issue?

**Comment by sinansonmez** [comment]
@AsisRout thanks for the changes. Could you please run `/update-branch`?

**Comment by M-ZubairAhmed** [comment]
> @sinansonmez @M-ZubairAhmed Can you please let me know if there's anything else i need to add for fixing this issue?

This is looking great thank you for fixing this

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by sinansonmez — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
