### PR TITLE
[MM-42586] Reaction toggle behavior

### LINKED ISSUE #19818: Reaction toggle behaviour
Related conversations:

  * [https://community.mattermost.com/core/pl/cr53mz791bn7idaecbrdjjnque](https://community.mattermost.com/core/pl/cr53mz791bn7idaecbrdjjnque)
  * [https://community.mattermost.com/core/pl/bjye8nwgn3yq3f6xa75hyugg6w](https://community.mattermost.com/core/pl/bjye8nwgn3yq3f6xa75hyugg6w)

Most of the ways to add a reaction to a post should have a toggle functionality. That is, if I already reacted to that post with that reaction, I have to remove the reaction. The places where that is not happening as of today are:

  * Quick Reaction (next to the three dot menu)
  * Emoji picker

There is one exception, the `+:emoji:` in a post where we already had that reaction, we should not make any call to the server (right now we are).

These behaviors have to be ensured both in webapp and mobile V2.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-42586

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

This PR includes two changes
1. Enabled toggling of emoji in Quick Reaction and Emoji Picker(currently only supports adding)
2. If we call +:emoji: in a post where we already had that reaction, we don't make any call to the server (right now we are).

#### Ticket Link

Fixes #19818 
Jira https://mattermost.atlassian.net/browse/MM-42586

#### Screenshots

https://github.com/mattermost/mattermost/assets/59413880/7a51ff94-de2a-4861-a6f4-520e419a3ebc

#### Release Note

```release-note
 Reaction toggle behavior
```

### CODE REVIEW

File: webapp/channels/src/actions/post_actions.ts [hunk 1]
```diff
@@ -140,6 +141,36 @@ function storeCommentDraft(rootPostId: string, draft: null) {
     };
 }
 
+export function submitReaction(postId: string, action: string, emojiName: string) {
+    return (dispatch: DispatchFunc, getState: GetStateFunc) => {
+        const state = getState() as GlobalState;
+        const getIsReactionAlreadyAddedToPost = makeGetIsReactionAlreadyAddedToPost();
+
+        const isReactionAlreadyAddedToPost = getIsReactionAlreadyAddedToPost(state, postId, emojiName);
```
Comment (larkox) [inline webapp/channels/src/actions/post_actions.ts:149]: This can be simplified to:

```suggestion
        const isReactionAlreadyAddedToPost  = makeGetIsReactionAlreadyAddedToPost()(state, postId, emojiName);
```

I think that the readibility is a bit better but 0/5. What do you think?

File: webapp/channels/src/actions/post_actions.ts [hunk 2]
```diff
@@ -140,6 +141,36 @@ function storeCommentDraft(rootPostId: string, draft: null) {
...
+        return {data: true};
+    };
+}
+
+export function toggleReaction(postId: string, emojiName: string) {
+    return (dispatch: DispatchFunc, getState: GetStateFunc) => {
+        const state = getState() as GlobalState;
+        const getIsReactionAlreadyAddedToPost = makeGetIsReactionAlreadyAddedToPost();
+
+        const isReactionAlreadyAddedToPost = getIsReactionAlreadyAddedToPost(state, postId, emojiName);
```
Comment (larkox) [inline webapp/channels/src/actions/post_actions.ts:165]: Same as my previous comment.

File: webapp/channels/src/actions/post_actions.ts [hunk 3]
```diff
@@ -140,6 +141,36 @@ function storeCommentDraft(rootPostId: string, draft: null) {
     };
 }
 
+export function submitReaction(postId: string, action: string, emojiName: string) {
+    return (dispatch: DispatchFunc, getState: GetStateFunc) => {
+        const state = getState() as GlobalState;
+        const getIsReactionAlreadyAddedToPost = makeGetIsReactionAlreadyAddedToPost();
```
Comment (larkox) [inline webapp/channels/src/actions/post_actions.ts:147]: I wonder if we can get rid of the `make` step.

File: webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
Comment (larkox) [inline webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx:1]: I see changes in `advanced_create_post` but I fail to see them in `advance_create_comment`. Are they not needed there? (I saw the changes in `actions/views/create_comment.tsx` and they might be enough, but better safe than sorry)

File: webapp/channels/src/utils/post_utils.test.tsx [hunk 4]
```diff
@@ -1319,3 +1319,37 @@ describe('PostUtils.getUserOrGroupFromMentionName', () => {
...
+                currentUserId,
+            },
+            posts: {
+                reactions: {
+                    post_id_1: {
+                        'current_user_id-smile': {
+                            emoji_name: 'smile',
+                            user_id: currentUserId,
+                            post_id: 'post_id_1',
+                        },
```
Comment (larkox) [inline webapp/channels/src/utils/post_utils.test.tsx:1338]: Just to cover all cases, add another reaction with the `sad` emoji for a different user. That way we make sure the test is also checking the case of "even if the post has that reaction made from another user, the function stills correctly says that the reaction is not yet added by the current user".

**Review by larkox — APPROVED** [review]
Great work! No strong comment to block the review, but a few comments on potential improvements.

**Comment by larkox** [comment]
@kyeongsoosoo Are you planning on submitting also the Mobile version of this, or just the the webapp version?

**Comment by Sudhanva-Nadiger** [comment]
> @kyeongsoosoo Are you planning on submitting also the Mobile version of this, or just the the webapp version?

In mobile clicking on the reacted emoji makes in disappear

**Comment by larkox** [comment]
@Sudhanva-Nadiger That also works like that in the webapp. This is a bit different. We are talking here about when using the emoji picker. It is not the most comfortable way to remove a reaction, but either way it should have toggle behavior (as this PR is doing).

**Comment by Sudhanva-Nadiger** [comment]
Ok cool

**Comment by kyeongsoosoo** [comment]
> @kyeongsoosoo Are you planning on submitting also the Mobile version of this, or just the the webapp version?

I'll submit a PR for the mobile version as well!

File: webapp/channels/src/actions/post_actions.ts (hunk 3 above)
Comment (devinbinnie) [reply webapp/channels/src/actions/post_actions.ts:147]: Shouldn't the `make` step be outside of the `dispatch` function actually?

**Review by devinbinnie — APPROVED** [review]
LGTM! Just that one non-blocking question.
Thanks @kyeongsoosoo!

**Review by abhijit-singh — APPROVED** [review]
Looks great based on the screencap. Thanks @kyeongsoosoo!

**Review by yasserfaraazkhan — APPROVED** [review]
tested this locally on mac chrome and desktop, as the spinwick are not running on pr.
Working as expected

File: webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
Comment (kyeongsoosoo) [reply webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx:1]: Sorry, the reply is a bit late😅 
`advanced_create_comment` component uses the action of `create_comment.tsx`.  So it's enough to just change the action of `create_comment.tsx`. 
https://github.com/mattermost/mattermost/blob/926142ca228a4ac1141d1529bbdd31c734503dfb/webapp/channels/src/components/advanced_create_comment/index.ts#L176C8-L176C8
