### PR TITLE
fix: status errcheck issues

### LINKED ISSUE #28528: Fix errcheck issues in server/channels/api4/status.go
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/api4/status.go`.

### What is `errcheck`?
`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behaviour. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- Remove the exception for `channels/api4/status.go` from the exceptions list for `errcheck` in `server/.golangci.yml`.
- Run `make golangci-lint` to get a list of all linter errors.
- Fix the errors by properly handling them.
- Run `make golangci-lint` again to ensure all errors are fixed.

#### Okay, but what does "properly handling" mean?
In general, errors should be returned to the caller. Non critical errors should be loggged, and function execution should continue. There are some exceptions to this rule, such as when the error is expected and should be ignored or when the error is handled in a different way. In such cases, a comment should be added to explain why the error is ignored.

In tests, errors should be checked using `require.NoError(t, err)` for errors of type `error` or `require.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `require.Error(t, err)` for errors of type `error` or `require.NotNil(t, err)` for errors of type `**model.AppError`.

Use `err` as the variable name for errors and `appErr` for `*model.AppError`. Avoid using variable names like `err1`, `err2`, etc. See [the Mattermost style guide](https://developers.mattermost.com/contribute/more-info/server/style-guide/#error-variable-names) for more information.

https://github.com/mattermost/mattermost/pull/28364 and https://github.com/mattermost/mattermost/pull/28376 can be used as examples of how to fix `errcheck` issues in the `api4` package.

-------------

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

If this ticket is already taken, please check out our other [Help Wanted tickets](https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22) of this campaign.

Thank you for your contributions to Mattermost!

----------------

JIRA: MM-60922

### PR DESCRIPTION
**Pull request by RS-labhub**
#### Summary
Fixed the errcheck issues

#### Ticket Link
fixes #28528 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

File: server/channels/api4/status.go [hunk 1]
```diff
@@ -78,7 +78,10 @@ func getUserStatusesByIds(c *Context, w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	w.Write(js)
+	if _, err := w.Write(js); err != nil {
+		c.Err = model.NewAppError("getUserStatusesByIds", "api.status.write_response.app_error", nil, "", http.StatusInternalServerError).Wrap(err)
+		return
+	}
```
Comment (hanzei) [inline server/channels/api4/status.go:84]: Similar comment as in the other PR: Please just log the error

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the PR :tada:

File: server/channels/api4/status.go (hunk 1 above)
Comment (RS-labhub) [reply server/channels/api4/status.go:84]: Okay okay.. Will fix all the requested changes in the PRs tomorrow... Right now I'm writing a blog, where I mentioned mattermost as one of the top repo to contribute... 🥰

Comment (RS-labhub) [reply server/channels/api4/status.go:84]: Done!

**Review by RS-labhub — COMMENTED** [review]
Done!

File: server/channels/api4/status.go [hunk 2]
```diff
@@ -78,7 +78,10 @@ func getUserStatusesByIds(c *Context, w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	w.Write(js)
+	if _, err := w.Write(js); err != nil {
+		c.Logger.Warn("Error while writing response", mlog.Err(err))
+		return
+	}
```
Comment (hanzei) [inline server/channels/api4/status.go:84]: Nit pick: Let's keep the code consistent with the rest of the code base
```suggestion
	if _, err := w.Write(js); err != nil {
		c.Logger.Warn("Error while writing response", mlog.Err(err))
	}
```

**Review by hanzei — APPROVED** [review]
LGTM :+1:

File: server/channels/api4/status.go (hunk 2 above)
Comment (RS-labhub) [reply server/channels/api4/status.go]: Sometimes I really don't know what I'm doing 😓

Sorry for this...

**Review by RS-labhub — COMMENTED** [review]
Done!

File: server/channels/api4/status.go (hunk 2 above)
Comment (hanzei) [reply server/channels/api4/status.go]: No need to be sorry. Mistakes happen. To all of us.

File: server/channels/api4/status.go [hunk 3]
```diff
@@ -106,7 +108,11 @@ func updateUserStatus(c *Context, w http.ResponseWriter, r *http.Request) {
 
 	currentStatus, err := c.App.GetStatus(c.Params.UserId)
 	if err == nil && currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
-		c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+		err = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+		if err != nil {
+			c.Err = err
+			return
+		}
 	}
```
Comment (agnivade) [inline server/channels/api4/status.go:116]: @hanzei - what are your thoughts on changing this to be more atomic?

```go
currentStatus, appErr := c.App.GetStatus(c.Params.UserId)
if appErr != nil {
  c.Err = appErr
  return
}
if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
  appErr = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
  if appErr != nil {
	c.Err = appErr
	return
  }
}
```

Comment (hanzei) [reply server/channels/api4/status.go:116]: Is it worth blocking the execution of the later code if `App.GetStatus` fails? I wonder what the side affects are if `App.GetStatus` continuously fails and the status doesn't get updated.

Comment (agnivade) [reply server/channels/api4/status.go:116]: If not, we should atleast log every error. Here, we are only executing the code if `appErr == nil` completely ignoring the fact that if `app.GetStatus` fails, there is no indication whatsoever as to why `DisableAutoResponder` was not executed.

Comment (hanzei) [reply server/channels/api4/status.go:116]: I'm fully supportive of logging the error :+1:

Comment (RS-labhub) [reply server/channels/api4/status.go:116]: And the error is logged!

```go
if err == nil && currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
		err = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
		if err != nil {
			c.Err = err
			return
		}
        }
```

Do you guys @hanzei @agnivade mean something different?

Comment (hanzei) [reply server/channels/api4/status.go:116]: If `c.App.GetStatus` error, we don't log the error.

Comment (agnivade) [reply server/channels/api4/status.go:116]: @RS-labhub - Please go through the above discussion again. We want to log the error from `c.App.GetStatus(c.Params.UserId)`. The code you posted above doesn't do that.

Comment (RS-labhub) [reply server/channels/api4/status.go:116]: Got it!! Pushing the changes soon!

**Review by RS-labhub — COMMENTED** [review]
Done!

**Comment by RS-labhub** [comment]
Postgres and MySQL tests are failing

File: server/.golangci.yml [hunk 4]
```diff
@@ -86,8 +86,9 @@ issues:
         channels/api4/remote_cluster.go|\
         channels/api4/role_test.go|\
         channels/api4/scheme_test.go|\
+        channels/api4/shared_channel_test.go|\
+        channels/api4/status_test.go|\
```
Comment (hanzei) [inline server/.golangci.yml:90]: That diff seems wrong

Comment (RS-labhub) [reply server/.golangci.yml]: I don't know what's causing the error. I previously solved the merged conflict too and it was all good that time. I removed these lines though.

**Review by RS-labhub — COMMENTED** [review]
Tried removing these lines. It will not create any impact as it's already been removed!

File: server/channels/api4/status.go (hunk 3 above)
Comment (agnivade) [reply server/channels/api4/status.go]: You have pushed my original suggestion, which is not what we want. We do not want to return in case of error from `GetStatus`, but just log it.

If you have any confusion, feel free to reach out to me on community.mattermost.com at agniva.de.sarker.

Comment (RS-labhub) [reply server/channels/api4/status.go]: @agnivade sorry the confusion, could you check it now?

File: server/channels/api4/status.go [hunk 5]
```diff
@@ -105,8 +107,15 @@ func updateUserStatus(c *Context, w http.ResponseWriter, r *http.Request) {
...
+	if err != nil {
+		c.Logger.Warn("Failed to get current status", mlog.Err(err))
+	}
+	if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
+		err = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+		if err != nil {
+			c.Err = err
+			return
+		}
 	}
```
Comment (hanzei) [inline server/channels/api4/status.go:119]: Let's wrap this in an `else` as I'm not sure what the default return value of `GetStatus` is
```suggestion
	}
	} else if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
		err = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
		if err != nil {
			c.Err = err
			return
		}
	}
```

Comment (RS-labhub) [reply server/channels/api4/status.go]: Committed directly as the suggestion

File: server/channels/api4/status.go [hunk 6]
```diff
@@ -105,8 +107,15 @@ func updateUserStatus(c *Context, w http.ResponseWriter, r *http.Request) {
...
 
 	currentStatus, err := c.App.GetStatus(c.Params.UserId)
-	if err == nil && currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
-		c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+	if err != nil {
+		c.Logger.Warn("Failed to get current status", mlog.Err(err))
+	}
+	} else if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
```
Comment (hanzei) [inline server/channels/api4/status.go:113]: That is one curly bracket too much
```suggestion
	} else if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
```

**Comment by RS-labhub** [comment]
If the test again fails, will do it manually! 🙂

My workspace is dead for now, so need some time

File: server/channels/api4/status.go [hunk 7]
```diff
@@ -105,8 +107,14 @@ func updateUserStatus(c *Context, w http.ResponseWriter, r *http.Request) {
...
-	if err == nil && currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
-		c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+	if err != nil {
+		c.Logger.Warn("Failed to get current status", mlog.Err(err))
+	} else if currentStatus.Status == model.StatusOutOfOffice && status.Status != model.StatusOutOfOffice {
+		err = c.App.DisableAutoResponder(c.AppContext, c.Params.UserId, c.IsSystemAdmin())
+		if err != nil {
+			c.Err = err
+			return
+		}
```
Comment (agnivade) [inline server/channels/api4/status.go:117]: I think we should log here again. Returning from here would change behavior from before.

Comment (RS-labhub) [reply server/channels/api4/status.go]: @agnivade done!

**Review by RS-labhub — COMMENTED** [review]
Could you review it now?

**Review by agnivade — APPROVED** [review]
Thanks for your patience with this @RS-labhub !

**Comment by RS-labhub** [comment]
> Thanks for your patience with this @RS-labhub !

I need to say this... Thanks @agnivade and @hanzei for your patience.

(few tests are failing, opening my workspace and fixing them)

**Review by hanzei — APPROVED** [review]
Thanks for bearing through the discussion :tada:
