### PR TITLE
Clicking on "remember my preference" in landing page does not tick the associated checkbox 

### LINKED ISSUE #26702: Landing page: clicking on "remember my preference" does not tick the associated checkbox
#### Summary

When going to the landing page of a Mattermost instance, I am given the options "View in Desktop App" and "View in Browser" with a checkbox "Remember my preference".

Clicking on "Remember my preference" does not tick the associated checkbox: one needs to click exactly on the checkbox. This a sign for a missing `<label>` which goes against [the guidelines from the Web Accessibility Initiative](https://www.w3.org/WAI/tutorials/forms/labels/). This can impair keyboard navigation or screen reader usage for instance.

The DOM structure there is indeed:
```html
<div class="get-app__preference">
    <button class="get-app__checkbox "></button>
    <span>Remember my preference</span>
</div>
```

#### Steps to reproduce

Observed on the landing page of a Mattermost instance (Team edition version 9.7).

#### Expected behavior

Clicking on the text "Remember my preference" should check / uncheck the associated checkbox.

#### Observed behavior (that appears unintentional) 

Only clicking on the checkbox works.
remember_my_pref

#### Possible fixes

Adding the missing `<label>` element (see guidelines above).

### PR DESCRIPTION
**Pull request by wetneb**
#### Summary

Adds a missing `<label>` element on the landing page to improve accessibility.

I transformed an existing `<div>` into a `<label>` to keep the structure simple. Because of the existing CSS class, this element already has `display: flex` so this will not cause any layout changes due to the change of element type.

#### Ticket Link

Fixes #26702.

##### Before
remember_my_pref 
##### After
working

#### Release Note

```release-note
NONE
```

### CODE REVIEW

File: webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx [hunk 1]
```diff
@@ -392,7 +392,7 @@ export default class LinkingLandingPage extends PureComponent<Props, State> {
                         />
                     </a>
                 </div>
-                <div className='get-app__preference'>
+                <label className='get-app__preference'>
```
Comment (M-ZubairAhmed) [inline webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx:395]: It is not a recommended practice to have button inside of a label. https://html.spec.whatwg.org/multipage/forms.html#the-label-element

if you would like you can improve all of this by good measure

We can instead use with correct styling! And we might have to get rid of the custom icon in favor of html checkbox

```
label
-- checkbox
-- text
label
```

Let me know if you would like to make improvements

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]

File: webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx (hunk 1 above)
Comment (wetneb) [reply webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx:383]: I definitely agree that it would be much cleaner to have a proper checkbox instead of a button masquerading as a checkbox. I have added commit 5667b35 which does that.

File: webapp/channels/src/sass/routes/_get-app.scss [hunk 2]
```diff
@@ -124,7 +124,7 @@
 }
 
 .get-app__preference {
-    display: flex;
+    display: block;
```
Comment (wetneb) [inline webapp/channels/src/sass/routes/_get-app.scss:127]: I made this change to preserve the vertical alignment of the checkbox and the text, after removing the custom styling of the checkbox below.

**Comment by wetneb** [comment]
In my opinion the visual differences after turning the button into a checkbox are acceptable:

new

File: webapp/channels/src/sass/routes/_get-app.scss (hunk 2 above)
Comment (M-ZubairAhmed) [reply webapp/channels/src/sass/routes/_get-app.scss:127]: thank you its is a lot better let me add UX team for the review @abhijit-singh

**Review by abhijit-singh — CHANGES_REQUESTED** [review]
Thank you @wetneb! I agree this is an improvement but I have a couple of requests:
1. Can we make sure that the cursor changes to a pointing hand while hovering on the checkbox or the label to make sure the user understands that's clickable? Adding `cursor: pointer;` should do it.
2. The label seems to be vertically misaligned with the checkbox. I'd recommend moving the label up by 3px.
image

**Comment by wetneb** [comment]
Good catch! I have changed the `margin-top: -2px` to `margin-top: 1px` to get the desired 3px offset.

On my side it looks like this on Firefox:
image
And on Chromium:
image

**Comment by wetneb** [comment]
@abhijit-singh @M-ZubairAhmed do you foresee any further changes to be made here? Let me know if I can be of any help :)

**Comment by abhijit-singh** [comment]
@M-ZubairAhmed Can you help getting a test server running here?

**Comment by wetneb** [comment]
Note: to try it out it can be useful to open the test server in a private browsing window, to make sure the landing page doesn't remember a previous preference for the web app or desktop app.

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh test server is up

File: webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx [hunk 3]
```diff
@@ -99,12 +98,11 @@ export default class LinkingLandingPage extends PureComponent<Props, State> {
         return landingPreference && landingPreference === LandingPreferenceTypes.MATTERMOSTAPP;
     };
 
-    handleChecked = () => {
-        // If it was checked, and now we're unchecking it, clear the preference
```
Comment (M-ZubairAhmed) [inline webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx:103]: i think this comment is still valid right?

File: webapp/channels/src/sass/routes/_get-app.scss [hunk 4]
```diff
@@ -138,26 +139,11 @@
     }
 }
 
-.get-app__checkbox {
+input[type="checkbox"].get-app__checkbox {
     width: 18px;
     height: 18px;
     padding: 0;
```
Comment (M-ZubairAhmed) [inline webapp/channels/src/sass/routes/_get-app.scss:145]: can you nest this inside of `get-app__preference` that way we dont have to use this selector for specificity `input[type="checkbox"].`

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]

**Review by larkox — APPROVED** [review]
LGTM, no extra comments.

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]
