### PR TITLE
[MM-57519] Fill the {time} parameter with a blank string in places where it isn't used

### LINKED ISSUE #26617: Custom status end time is not shown correctly
#### Summary
Custom status end time is not shown correctly on hover

#### Steps to reproduce
1. Set a custom status with end time
2. Click your profile picture to see your custom status

#### Expected behavior
(Until Tomorrow at 03:15)

#### Observed behavior (that appears unintentional) 
(Until {time} Tomorrow at 03:15)
Screenshot from 2024-03-27 23-20-15

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
A recent change added a `{time}` parameter to the translation for the custom status expiry time, which wasn't accounted for in all components, so this PR just adds a blank string in the `expiry_time` component where the extra parameter isn't needed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57519
Fixes #26617

```release-note
NONE
```

### CODE REVIEW

File: webapp/channels/src/components/custom_status/expiry_time.tsx [hunk 1]
```diff
@@ -55,7 +55,8 @@ const ExpiryTime = ({time, timezone, className, showPrefix, withinBrackets}: Pro
         <>
             <FormattedMessage
                 id='custom_status.expiry.until'
-                defaultMessage='Until'
+                defaultMessage='Until {time}'
+                values={{time: ''}}
```
Comment (larkox) [inline webapp/channels/src/components/custom_status/expiry_time.tsx:59]: Shouldn't this be instead something like:
```
if (time) {
   <FormattedMessage ... />
}
```
If not we will show something like `Until  ` and nothing after it, right?

**Review by larkox — CHANGES_REQUESTED** [review]

File: webapp/channels/src/components/custom_status/expiry_time.tsx (hunk 1 above)
Comment (devinbinnie) [reply webapp/channels/src/components/custom_status/expiry_time.tsx:59]: Looks fine to me:
image

Comment (larkox) [reply webapp/channels/src/components/custom_status/expiry_time.tsx:59]: I feel this is wrong. The two whitespaces are well handled, but still... they are used in a different way even being the same string. In Spanish I would say slightly different until a time, and until a date.

On top of that, maybe this makes more sense if the value instead of the empty string is the Timestamp value we are using later.

And the withing brackets should also consider language dependent brackets...

Probably we should look deeper into this, but I am going to approve to get the "most glaring issue" be fixed fast.

**Review by larkox — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
image
