### PR TITLE
[MM-61097] Fix errcheck issues in server/channels/app/bot.go

### LINKED ISSUE #28776: Fix errcheck issues in server/channels/app/bot.go
At Mattermost, we are committed to maintaining a high standard of code quality, reliability, and security. To further enhance this, we are launching a community campaign to integrate the [`errcheck`](https://github.com/kisielk/errcheck) linter across the Mattermost codebase.

This Help Wanted ticket is about fixing the linter issues reported by `errcheck` in `channels/app/bot.go`.

### What is `errcheck`?
`errcheck` is a tool that automatically identifies places in Go code where errors are returned but not checked. In Go, error handling is a critical part of writing robust applications, and ignoring returned errors can lead to bugs, crashes, or unintended behaviour. By integrating `errcheck` into the codebase, we can ensure that error handling is consistently and properly managed across the project.

### Tasks
- Remove the exception for `channels/app/bot.go` from the exceptions list for `errcheck` in `server/.golangci.yml`.
- Run `make golangci-lint` to get a list of all linter errors.
- Fix the errors by properly handling them.
- Run `make golangci-lint` again to ensure all errors are fixed.

#### Okay, but what does "properly handling" mean?
In general, errors should be returned to the caller. Non critical errors should be loggged, and function execution should continue. There are some exceptions to this rule, such as when the error is expected and should be ignored or when the error is handled in a different way. In such cases, a comment should be added to explain why the error is ignored.

In tests, errors should be checked using `require.NoError(t, err)` for errors of type `error` or `require.Nil(t, err)` for errors of type `**model.AppError`.
If an error is expected, it should be checked using `require.Error(t, err)` for errors of type `error` or `require.NotNil(t, err)` for errors of type `**model.AppError`.

Use `err` as the variable name for errors and `appErr` for `*model.AppError`. Avoid using variable names like `err1`, `err2`, etc. See [the Mattermost style guide](https://developers.mattermost.com/contribute/more-info/server/style-guide/#error-variable-names) for more information.

https://github.com/mattermost/mattermost/pull/28364 and https://github.com/mattermost/mattermost/pull/28376 can be used as examples of how to fix `errcheck` issues in the `api4` package.

-------------

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on the Mattermost Community server, where you can discuss questions with community members and the Mattermost core team.
For technical advice or questions, please [join our "Developers Server" community channel](https://community.mattermost.com/core/channels/developers-server).
You can also reach out to @hanzei either on this ticket or on [the Mattermost Community server](https://community.mattermost.com).

For new contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

If this ticket is already taken, please check out our other [Help Wanted tickets](https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22) of this campaign.

Thank you for your contributions to Mattermost!

----------------

JIRA: MM-61097

### PR DESCRIPTION
**Pull request by RS-labhub**
#### Summary
Fixed the errcheck issues

#### Ticket Link
fixes #28776 
Jira [MM-61097](https://mattermost.atlassian.net/browse/MM-61097)

#### Release Note
```release-note
NONE
```

[MM-61097]: https://mattermost.atlassian.net/browse/MM-61097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by RS-labhub** [comment]
@hanzei could you take a quick look at this PR. Is this how you want it?

File: server/channels/app/bot.go [hunk 1]
```diff
@@ -124,7 +124,9 @@ func (a *App) CreateBot(rctx request.CTX, bot *model.Bot) (*model.Bot, *model.Ap
 
 	savedBot, nErr := a.Srv().Store().Bot().Save(bot)
 	if nErr != nil {
-		a.Srv().Store().User().PermanentDelete(rctx, bot.UserId)
+		if err := a.Srv().Store().User().PermanentDelete(rctx, bot.UserId); err != nil {
+			return nil, model.NewAppError("CreateBot", "app.bot.createbot.internal_error", nil, "", http.StatusInternalServerError).Wrap(err)
+		}
```
Comment (hanzei) [inline server/channels/app/bot.go:129]: I'm concerned that if both `Bot().Save` and `User().PermanentDelete` fail, the error returned by `User().PermanentDelete` is neither logged nor returned.

I suggest that we log the error from `User().PermanentDelete` instead of returning it.

Comment (RS-labhub) [reply server/channels/app/bot.go:129]: Yeah, make sense. I was bit confused about this one

**Review by RS-labhub — COMMENTED** [review]
Logged the errors!

File: server/channels/app/bot.go [hunk 2]
```diff
@@ -124,7 +124,9 @@ func (a *App) CreateBot(rctx request.CTX, bot *model.Bot) (*model.Bot, *model.Ap
 
 	savedBot, nErr := a.Srv().Store().Bot().Save(bot)
 	if nErr != nil {
-		a.Srv().Store().User().PermanentDelete(rctx, bot.UserId)
+		if err := a.Srv().Store().User().PermanentDelete(rctx, bot.UserId); err != nil {
+			a.Log().Error("Failed to permanently delete user", mlog.Err(err))
```
Comment (hanzei) [inline server/channels/app/bot.go:128]: Let's use the request logger
```suggestion
			rctx.Logger().Error("Failed to permanently delete user", mlog.Err(err))
```

File: server/channels/app/bot.go [hunk 3]
```diff
@@ -227,7 +229,9 @@ func (a *App) getOrCreateBot(rctx request.CTX, botDef *model.Bot) (*model.Bot, *
 		//save the bot
 		savedBot, nErr := a.Srv().Store().Bot().Save(botDef)
 		if nErr != nil {
-			a.Srv().Store().User().PermanentDelete(rctx, savedBot.UserId)
+			if err := a.Srv().Store().User().PermanentDelete(rctx, savedBot.UserId); err != nil {
+				a.Log().Error("Failed to permanently delete user", mlog.Err(err))
```
Comment (hanzei) [inline server/channels/app/bot.go:233]: Same here
```suggestion
				rctx.Logger().Error("Failed to permanently delete user", mlog.Err(err))
```

File: server/channels/app/bot.go (hunk 2 above)
Comment (hanzei) [inline server/channels/app/bot.go:128]: I wonder if the error message could be more descriptive. It's currently not clear, why the code deletes the users.

Comment (RS-labhub) [reply server/channels/app/bot.go:128]: How about this:
> "Failed to permanently delete the user after bot save failure"

**Review by RS-labhub — COMMENTED** [review]
P.S: It's ready for review!

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by crspeller — APPROVED** [review]
